apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "5,15,25,35,45,55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-job-sa
          securityContext:
            fsGroup: 1000  # ✅ 기본 그룹 권한 설정 (일부 PVC에는 적용 안 될 수도 있음)
            runAsUser: 1000       # 컨테이너 내부 사용자 ID 변경 (비-root)
            runAsGroup: 1000      # 그룹 변경
            fsGroup: 1000         # 파일 시스템 그룹 변경 (NFS, Filestore에 적용 가능)
          containers:
            - name: backup-uploader
              image: google/cloud-sdk:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c"]
              args:
                - |
                  chmod +x /scripts/upload_backup.sh
                  /scripts/upload_backup.sh
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/key.json
              volumeMounts:
                - name: backup-storage
                  mountPath: /palworld/backups
                  readOnly: false
                - name: scripts
                  mountPath: /scripts
                - name: gcs-secret
                  mountPath: /secrets
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}
            - name: scripts
              configMap:
                name: {{ .Release.Name }}-backup-script
                defaultMode: 0755 
            - name: gcs-secret
              secret:
                secretName: gcs-key
