apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "5,15,25,35,45,55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-job-sa
          containers:
            - name: backup-uploader
              image: google/cloud-sdk:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c"]
              args:
                - |
                  chmod +x /scripts/upload_backup.sh
                  /scripts/upload_backup.sh
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/key.json
              volumeMounts:
                - name: backup-storage
                  mountPath: /palworld/backups
                - name: scripts
                  mountPath: /scripts
                - name: gcs-secret
                  mountPath: /secrets
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}
            - name: scripts
              configMap:
                name: {{ .Release.Name }}-backup-script
            - name: gcs-secret
              secret:
                secretName: gcs-key  # ✅ 이제 현재 네임스페이스에 있는 Secret을 사용
