apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backup-script
  namespace: {{ .Release.Namespace }}
data:
  upload_backup.sh: |
    #!/bin/bash
    BACKUP_DIR="/palworld/backups"
    GCS_BUCKET="etd-test-bucket"
    GCS_FOLDER="backup"

    # 최신 백업 파일 찾기
    LATEST_BACKUP=$(ls -t $BACKUP_DIR/*.tar.gz | head -n 1)

    if [[ -z "$LATEST_BACKUP" ]]; then
        echo " No backup files found in $BACKUP_DIR"
        exit 1
    fi

    echo " Uploading $LATEST_BACKUP to gs://$GCS_BUCKET/$GCS_FOLDER/"
    gsutil cp "$LATEST_BACKUP" "gs://$GCS_BUCKET/$GCS_FOLDER/"

    if [[ $? -eq 0 ]]; then
        echo " Upload successful! Deleting local file: $LATEST_BACKUP"
        rm -f "$LATEST_BACKUP"
    else
        echo " Upload failed!"
        exit 1
    fi
