apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "5,15,25,35 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-job-sa
          initContainers:
            - name: secret-copier
              image: bitnami/kubectl:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  kubectl get secret gcs-key -n gcs -o yaml | \
                  sed 's/namespace: gcs/namespace: {{ .Release.Namespace }}/' | \
                  kubectl apply -f -
          containers:
            - name: backup-uploader
              image: google/cloud-sdk:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c"]
              args:
                - |
                  chmod +x /scripts/upload_backup.sh
                  /scripts/upload_backup.sh
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/key.json
              volumeMounts:
                - name: backup-storage
                  mountPath: /palworld/backups
                - name: scripts
                  mountPath: /scripts
                - name: gcs-secret
                  mountPath: /secrets
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: test
            - name: scripts
              configMap:
                name: {{ .Release.Name }}-backup-script
            - name: gcs-secret
              secret:
                secretName: gcs-key  # ✅ 이제 현재 네임스페이스에 있는 Secret을 사용
