---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.palworld.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.palworld.name }}
    spec:
      containers:
        - name: {{ .Values.palworld.name }}
          image: thijsvanloef/palworld-server-docker # 추후 이미지 업데이트 고려해보기
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8211
              name: server
              protocol: UDP
            - containerPort: 27015
              name: query
              protocol: UDP
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.palworld.name }}-secrets
                  key: rconPassword
          envFrom:
            - configMapRef:
                name: {{ .Values.palworld.name }}-cm
          volumeMounts:
            - mountPath: /palworld
              name: datadir
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ .Values.palworld.name }}
