---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.palworld.name }}-cm
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
